import { CONTROL_CENTER_HTML } from "./ui.js";

// Local QA artifact only: uses shipped primitive CSS, never a production route.
const styleStart = CONTROL_CENTER_HTML.indexOf("<style>");
const styleEnd = CONTROL_CENTER_HTML.indexOf("</style>") + "</style>".length;
const primitiveStyles = CONTROL_CENTER_HTML.slice(styleStart, styleEnd);

export const PRIMITIVE_SHOWCASE_HTML = String.raw`<!doctype html>
<html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="JK shared primitive state verification, not production work data.">
<title>JK primitive showcase</title>${primitiveStyles}</head><body>
<a class="skip-link" href="#showcase">Skip to primitives</a>
<main class="content" id="showcase" tabindex="-1">
<div class="page-head"><div><h1>JK primitive showcase</h1><p class="sub">Isolated examples for state verification. No product data or API actions.</p></div></div>
<section class="section-block" aria-labelledby="action-title"><h2 class="section-title" id="action-title">Actions / keyboard focus / press</h2>
<div class="actions"><button class="btn primary" id="showcase-primary">Primary action</button><button class="btn">Secondary</button><button class="btn ghost">Ghost</button><button class="btn danger">Deny</button><button class="btn small">Compact</button><button class="btn" disabled>Disabled</button><button class="btn" aria-busy="true" disabled>Processing</button><button class="btn" data-state="success">Complete</button><button class="btn" data-state="error">Retry action</button></div></section>
<section class="section-block" aria-labelledby="nav-title"><h2 class="section-title" id="nav-title">Navigation</h2><nav class="nav" aria-label="Showcase navigation"><button class="active" aria-current="page">Selected destination</button><button>Other destination</button></nav><nav class="project-nav" aria-label="Showcase projects"><button aria-current="true"><span>선택한 프로젝트</span></button><button><span>Long-project-name-that-exceeds-available-navigation-width-and-must-not-overflow</span></button></nav></section>
<section class="section-block" aria-labelledby="status-title"><h2 class="section-title" id="status-title">Statuses</h2><div class="badges"><span class="badge">Unknown</span><span class="badge active">Current phase</span><span class="badge ok">Pass</span><span class="badge warn">Waiting</span><span class="badge danger">Failed</span><span class="badge default">Information</span><span class="status-chip">Snapshot <strong>Ready</strong></span></div>
<div class="host-row" data-host-state="online"><div><strong>Hub example</strong><div class="sub">Control and approval service</div></div><span class="badge ok">Online</span></div><div class="host-row" data-host-state="offline"><div><strong>Windows example</strong><div class="sub">Selected target unavailable; execution blocked</div></div><span class="badge warn">Offline</span></div><div class="host-row" data-host-state="unknown"><strong>Unreported host</strong><span class="badge">Unknown</span></div></section>
<section class="section-block" aria-labelledby="work-title"><h2 class="section-title" id="work-title">Work / idle / content stress</h2><article class="work-surface"><div class="dashboard-eyebrow">Current work example</div><h3 class="dashboard-task">현재 작업과 검증 결과를 읽기 쉽게 표시합니다</h3><dl class="work-ledger"><div><dt>Project</dt><dd>Example only</dd></div><div><dt>Execution location</dt><dd>Unknown until target is reported</dd></div><div><dt>Verification</dt><dd>Not reported</dd></div></dl><div class="work-result"><p class="run-summary-note">This is an isolated primitive specimen, not an invented dashboard result.</p></div><div class="workflow-strip"><div class="workflow-step done"><span class="workflow-dot"></span><span>discover</span></div><div class="workflow-step active"><span class="workflow-dot"></span><span>verify</span></div><div class="workflow-step"><span class="workflow-dot"></span><span>release</span></div></div></article><div class="empty">No work history available.</div><div class="empty" role="status">Loading snapshot...</div><div class="empty" role="alert">Snapshot unavailable. Refresh to retry.</div></section>
<section class="section-block" aria-labelledby="attention-title"><h2 class="section-title" id="attention-title">Attention / empty / command evidence</h2><div class="attention-empty" data-attention-state="empty">No approvals waiting</div><div class="attention-surface" data-attention-state="pending"><h3 class="section-title">Approval required</h3><div class="attention-row"><div class="goal-title">Example request</div><div class="mono" data-execution-location data-target-kind="remote">Windows example / C:\workspace\a-very-long-unbroken-project-name-that-must-wrap-without-clipping</div><p class="sub">Review the persisted execution target and scope.</p><button class="btn primary">Review approval</button></div></div><div class="goal-row approval-card"><div class="role-head"><div class="goal-title">Approval actions specimen</div><div class="approval-actions"><button class="btn primary">이 작업 30분 승인 · 권장</button><button class="btn">승인하고 실행</button><button class="btn danger">거절</button></div></div><pre class="mono approval-command">command --example https://example.invalid/a-very-long-unbroken-path-that-must-wrap-rather-than-clipping-command-evidence</pre><div class="badges"><span class="badge danger">Destructive</span><span class="badge warn">Network</span></div></div></section>
<section class="section-block" aria-labelledby="rows-title"><h2 class="section-title" id="rows-title">Records / disclosure / external link</h2><div class="log-list"><div class="log-row"><div class="log-type">Example event</div><div class="log-detail">Long Korean task detail: 프로젝트의 최근 결과와 검증 기록을 보여 주는 행입니다.</div><div class="mono">Recorded timestamp</div></div><div class="log-row fresh"><div class="log-type">New event state</div><div class="log-detail">One finite entry, never a perpetual activity animation.</div><div class="mono">Example only</div></div></div><div class="role-card active"><div class="role-name">Selected role specimen</div><div class="role-desc">Shared role primitive</div><div class="actions"><button class="btn">Apply</button></div></div><div class="goal-row"><div class="goal-title">Goal specimen</div><ul class="progress-list"><li>Example completed item</li></ul></div><details class="disclosure"><summary>Details specimen</summary><dl class="kv"><dt>Mode</dt><dd>Example</dd><dt>Long value</dt><dd class="mono">0123456789012345678901234567890123456789012345678901234567890123456789</dd></dl></details><a class="quick-link" href="https://example.invalid" target="_blank" rel="noopener noreferrer"><div class="quick-link-copy"><div class="quick-link-title">External link specimen</div><div class="quick-link-note">Not a production Quick Link</div></div><span class="quick-link-arrow" aria-hidden="true">↗</span></a></section>
<section class="section-block" aria-labelledby="form-title"><h2 class="section-title" id="form-title">Native form controls / invalid / disabled</h2><div class="form-grid"><div class="field"><label for="spec-name">Name</label><input class="input" id="spec-name" value="프로젝트"></div><div class="field"><label for="spec-select">Executor</label><select class="select" id="spec-select"><option>OCI Hub</option><option>Windows executor</option></select></div><div class="field"><label for="spec-disabled">Disabled field</label><input class="input" id="spec-disabled" disabled value="Read only"></div><div class="field"><label for="spec-invalid">Invalid field</label><input class="input" id="spec-invalid" aria-invalid="true" aria-describedby="spec-error"><span class="sub" id="spec-error">A name is required.</span></div><div class="field full"><label for="spec-text">Instructions</label><textarea class="textarea" id="spec-text">Long-form Korean and English input</textarea></div></div><label class="check"><input type="checkbox" checked>Read files</label><button class="btn" id="open-spec-dialog">Open dialog</button><button class="btn" id="show-spec-toast">Show feedback</button></section>
</main><dialog id="spec-dialog" aria-labelledby="spec-dialog-title"><div class="dialog-head"><strong id="spec-dialog-title">Dialog specimen</strong></div><div class="dialog-body">Native focus containment, Escape and return focus.</div><div class="dialog-foot"><button class="btn" id="close-spec-dialog">Close</button></div></dialog><div class="toast" id="spec-toast" role="status">Feedback specimen</div><script>
document.getElementById('open-spec-dialog').addEventListener('click', () => document.getElementById('spec-dialog').showModal());
document.getElementById('close-spec-dialog').addEventListener('click', () => document.getElementById('spec-dialog').close());
document.getElementById('show-spec-toast').addEventListener('click', () => document.getElementById('spec-toast').classList.toggle('show'));
</script></body></html>`;
