export const MASS_ULW_ACTION_TOOL_NAME = "mass_ulw_execute";

export const MASS_ULW_ACTION_ROUTE = {
  path: "/actions/mass-ulw-execute",
  tool: MASS_ULW_ACTION_TOOL_NAME,
  operationId: MASS_ULW_ACTION_TOOL_NAME,
  summary: "Execute an approved MASS ULW plan",
  description:
    "Execute the exact MASS ULW dependency-wave plan previously approved and persisted by goal_loop. The current ChatGPT session supplies one Codex-style patch per approved lane; JK applies them in isolated private checkouts, verifies dependency waves, merges them, and runs one final verifier. No OMO or separate model/provider is required.",
  schema: "MassUlwExecuteInput",
} as const;

export const MASS_ULW_EXECUTE_INPUT_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: [
    "projectId",
    "loopId",
    "planFingerprint",
    "workSessionId",
    "lanePatches",
    "laneVerificationCommandIds",
    "finalVerificationCommandId",
  ],
  properties: {
    projectId: { type: "string", minLength: 1 },
    loopId: {
      type: "string",
      pattern: "^[A-Za-z0-9][A-Za-z0-9._-]{0,119}$",
      description: "Loop id whose approved MASS ULW plan was persisted by goal_loop.",
    },
    planFingerprint: {
      type: "string",
      pattern: "^[a-f0-9]{64}$",
      description: "Exact approved plan fingerprint returned by goal_loop.",
    },
    workSessionId: {
      type: "string",
      pattern: "^ws_[A-Za-z0-9_.-]+$",
      maxLength: 120,
    },
    lanePatches: {
      type: "object",
      additionalProperties: { type: "string", minLength: 1, maxLength: 10485760 },
      description: "Map every approved lane id to one Codex-style *** Begin Patch / *** End Patch envelope generated by the current ChatGPT session. Use an empty patch envelope for a read-only lane.",
    },
    laneVerificationCommandIds: {
      type: "object",
      additionalProperties: { type: "string", minLength: 1, maxLength: 200 },
      description: "Map of every approved lane id to a manifest-discovered verifier command id.",
    },
    finalVerificationCommandId: { type: "string", minLength: 1, maxLength: 200 },
    timeoutSec: { type: "integer", minimum: 1, maximum: 3600 },
  },
} as const;
